spring.datasource.url=jdbc:postgresql://postgres:5432/databinder
spring.datasource.username=admin
spring.datasource.password=admin

scraper.base-url=http://scraper-api:8000

scheduler.tick-rate-ms=60000
scraper.delay-ms=4000

app.cors.allowed-origins=http://localhost:4200,https://consistently-organ-pan-southeast.trycloudflare.com